import json
import threading
from urllib.request import urlopen
from twilio.rest import Client

# Required information to the SMS sending
MY_NUMBER = 'your phone'
TWILIO_NUMBER = 'number generated by twilio'
ACCOUNT_SID = "your twilio account id"
AUTH_TOKEN = "your twilio auth token"
CLIENT = Client(ACCOUNT_SID, AUTH_TOKEN)

#Take the price from localbitcoins, bitstamp, usd price and Mercadobitcoin and foxbit
urlBTCUSD = 'https://www.bitstamp.net/api/ticker/'
urlBRL = 'http://api.fixer.io/latest?base=USD'
urlMercado = 'https://www.mercadobitcoin.net/api/BTC/ticker/'
urlFOXBIT = 'https://api.blinktrade.com/api/v1/BRL/ticker?crypto_currency=BTC'
urlLocalJson = 'https://localbitcoins.com/buy-bitcoins-online/USD/.json'

json_obj_BTCUSD = urlopen(urlBTCUSD).read().decode('utf-8')
json_obj_BRL = urlopen(urlBRL).read().decode('utf-8')
json_obj_Mercado = urlopen(urlMercado).read().decode('utf-8')
json_obj_FOXBIT = urlopen(urlFOXBIT).read().decode('utf-8')

btc = json.loads(json_obj_BTCUSD)
brl = json.loads(json_obj_BRL)
mb = json.loads(json_obj_Mercado)
fb = json.loads(json_obj_FOXBIT)

btcUSDPrice = float(btc['last'])
usdBRL = float(brl['rates']['BRL'])
mercadob = float(mb['ticker']['last'])
foxbit = float(fb['last'])

btcUSD2BRL = btcUSDPrice * usdBRL
btcBRLAverage = (mercadob + foxbit) / 2
difference = (abs(btcBRLAverage - btcUSD2BRL)) / btcBRLAverage * 100.0

#print('%.2f' %btcBRLAverage)
#print('%.2f' %btcUSD2BRL)
#print('%.2f' %difference)

urlUSDV = urlBRL
urlLCB = urlLocalJson
    
json_obj_USD = urlopen(urlUSDV).read().decode('utf-8')
json_obj_LocalBtc = urlopen(urlLCB).read().decode('utf-8')

usdPrice = json.loads(json_obj_USD)
offer = json.loads(json_obj_LocalBtc)

usd2BRL = float(usdPrice['rates']['BRL'])

position = 0

#Fees
#mbFee = 2% p 2.50
#fbFee = 2% p 9.00
#wuFee = 12.00
#lbFee = 1%
#amnt = 3500.00 #BRL
totalFee = 200

size = len(offer['data']['ad_list'][position]['data']['profile'])

def SMS(ID, profit):
    text = 'Take a look on the offer: {0} - Possible profit: {1:.2f} percent.'.format(str(ID), profit)
    message = CLIENT.messages.create(to=MY_NUMBER,
                                     from_=TWILIO_NUMBER,
                                     body=text)
    print('SMS Sent')

def working():
    position = 0
    for i in range(size):
        position += 1
        seller = offer['data']['ad_list'][position]['data']['profile']['username']
        offerID = offer['data']['ad_list'][position]['data']['ad_id']
        price = float(offer['data']['ad_list'][position]['data']['temp_price_usd'])
        method = offer['data']['ad_list'][position]['data']['online_provider']
        if 'WU' in method:
            print('Seller: %s - Offer ID: %s  - by the price: %f - for the method: %s' %(seller, offerID, price, method))
            sellerBTC2BRL = usd2BRL * price
            print('Price in BRL: %.2f' %sellerBTC2BRL)
            diffSeller2BR = (abs(btcBRLAverage - sellerBTC2BRL - totalFee)) / btcBRLAverage * 100
            print('>>> Possible profit: %.2f percent' %(diffSeller2BR))
            if diffSeller2BR > 0: #You set here when send the allert. In my case if the profit > than 15%
                SMS(offerID, diffSeller2BR)
def contador():
    threading.Timer(20, contador).start()
    working()

contador()
